import 'package:flutter/material.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedbillpaymentformwidget/generated/GeneratedBarsWidget7.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedbillpaymentformwidget/generated/GeneratedGroup12781Widget.dart';

/* Frame Bill Payment Form
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBillPaymentFormWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 630.0,
                child: GeneratedGroup12781Widget(),
              )
            ]),
      ),
    ));
  }
}
