import 'package:flutter/material.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedcreatefixeddepositwidget/generated/GeneratedCardListWidget2.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedcreatefixeddepositwidget/generated/GeneratedGroup12764Widget.dart';

/* Frame Create Fixed Deposit
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCreateFixedDepositWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -16.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 391.0,
                height: 656.0,
                child: GeneratedCardListWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 140.0,
                child: GeneratedGroup12764Widget(),
              )
            ]),
      ),
    ));
  }
}
