import 'package:flutter/material.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedhomewidget/generated/GeneratedGroup12761Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedhomewidget/generated/GeneratedGroup12759Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedhomewidget/generated/GeneratedGroup12760Widget.dart';

/* Frame Home 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1197.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1170.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 148.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 299.0,
                              child: GeneratedGroup12761Widget(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 140.0,
                              child: GeneratedGroup12759Widget(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 487.0,
                              right: null,
                              bottom: null,
                              width: 358.0,
                              height: 710.0,
                              child: GeneratedGroup12760Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
