import 'package:flutter/material.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedfundtransferregisteraccountwidget/generated/GeneratedBarsWidget12.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedfundtransferregisteraccountwidget/generated/GeneratedGroup12790Widget.dart';

/* Frame Fund Transfer / Register Account
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFundTransferRegisterAccountWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsWidget12(),
              ),
              Positioned(
                left: -1.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 612.0,
                child: GeneratedGroup12790Widget(),
              )
            ]),
      ),
    ));
  }
}
