import 'package:flutter/material.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generateddrawerwidget/generated/GeneratedGroup12796Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generateddrawerwidget/generated/GeneratedArrow_drop_down_circleWidget4.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generateddrawerwidget/generated/GeneratedArrow_drop_down_circleWidget5.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generateddrawerwidget/generated/GeneratedVectorWidget68.dart';

/* Frame Drawer
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDrawerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 279.0,
      height: 823.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 279.0,
              height: 823.0,
              child: GeneratedGroup12796Widget(),
            ),
            Positioned(
              left: 79.0,
              top: 134.0,
              right: null,
              bottom: null,
              width: 7.287313461303711,
              height: 7.0,
              child: GeneratedArrow_drop_down_circleWidget4(),
            ),
            Positioned(
              left: 79.0,
              top: 234.0,
              right: null,
              bottom: null,
              width: 6.072761535644531,
              height: 5.833333492279053,
              child: GeneratedVectorWidget68(),
            ),
            Positioned(
              left: 78.0,
              top: 280.0,
              right: null,
              bottom: null,
              width: 7.287313461303711,
              height: 7.0,
              child: GeneratedArrow_drop_down_circleWidget5(),
            )
          ]),
    ));
  }
}
