import 'package:flutter/material.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedsplashligtwidget/generated/Generated2021TeamMERNsWidget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedsplashligtwidget/generated/GeneratedSeylanBank12Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedsplashligtwidget/generated/GeneratedFrame12731Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedsplashligtwidget/generated/GeneratedSeylanBank11Widget.dart';

/* Frame Splash / Ligt
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashLigtWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 115.0,
                top: 753.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 12.0,
                child: Generated2021TeamMERNsWidget(),
              ),
              Positioned(
                left: -470.0,
                top: -222.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 225.0,
                child: GeneratedSeylanBank11Widget(),
              ),
              Positioned(
                left: 88.0,
                top: 79.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 112.5,
                child: GeneratedSeylanBank12Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 480.0,
                child: GeneratedFrame12731Widget(),
              )
            ]),
      ),
    ));
  }
}
