import 'package:flutter/material.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedfundtransferownaccountwidget/generated/GeneratedGroup12789Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedfundtransferownaccountwidget/generated/GeneratedBarsWidget13.dart';

/* Frame Fund Transfer / Own account
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFundTransferOwnaccountWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsWidget13(),
              ),
              Positioned(
                left: -1.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 606.0,
                child: GeneratedGroup12789Widget(),
              )
            ]),
      ),
    ));
  }
}
