import 'package:flutter/material.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedatmlocatorwidget/generated/GeneratedHomeWidget1.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedatmlocatorwidget/generated/GeneratedFrame20Widget.dart';

/* Frame ATM Locator
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedATMLocatorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -9.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 715.0,
                child: GeneratedHomeWidget1(),
              ),
              Positioned(
                left: 1.0,
                top: 726.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 86.0,
                child: GeneratedFrame20Widget(),
              )
            ]),
      ),
    ));
  }
}
