import 'package:flutter/material.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedfundtransferregisteredaccountwidget/generated/GeneratedGroup12791Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedfundtransferregisteredaccountwidget/generated/GeneratedBarsWidget11.dart';

/* Frame Fund Transfer / Registered account
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFundTransferRegisteredaccountWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1094.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1094.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 88.0,
                              child: GeneratedBarsWidget11(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 108.0,
                              right: null,
                              bottom: null,
                              width: 376.0,
                              height: 916.0,
                              child: GeneratedGroup12791Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
