import 'package:flutter/material.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedaccounthistorycalendarwidget/generated/GeneratedComponent1Elevation4Widget.dart';

/* Frame AccountHistoryCalendar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAccountHistoryCalendarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 326.0,
      height: 422.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 326.0,
              height: 422.0,
              child: GeneratedComponent1Elevation4Widget(),
            )
          ]),
    ));
  }
}
