import 'package:flutter/material.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedrequestbankstatementwidget/generated/GeneratedFrame12720Widget2.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedrequestbankstatementwidget/generated/GeneratedBarsWidget10.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedrequestbankstatementwidget/generated/GeneratedGroup12794Widget.dart';

/* Frame Request Bank Statement
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRequestBankStatementWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 118.5,
                right: null,
                bottom: null,
                width: 375.0,
                height: 56.0,
                child: GeneratedFrame12720Widget2(),
              ),
              Positioned(
                left: 19.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 422.0,
                child: GeneratedGroup12794Widget(),
              )
            ]),
      ),
    ));
  }
}
