import 'package:flutter/material.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedbillpaymenthomewidget/generated/GeneratedGroup12774Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedbillpaymenthomewidget/generated/GeneratedGroup12780Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedbillpaymenthomewidget/generated/GeneratedGroup12779Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedbillpaymenthomewidget/generated/GeneratedGroup12775Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedbillpaymenthomewidget/generated/GeneratedGroup12778Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedbillpaymenthomewidget/generated/GeneratedGroup12776Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedbillpaymenthomewidget/generated/GeneratedGroup12777Widget.dart';

/* Frame Bill Payment  Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBillPaymentHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 39.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedGroup12775Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedGroup12780Widget(),
              ),
              Positioned(
                left: 205.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedGroup12779Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedGroup12778Widget(),
              ),
              Positioned(
                left: 204.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedGroup12777Widget(),
              ),
              Positioned(
                left: 205.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedGroup12776Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 178.0,
                child: GeneratedGroup12774Widget(),
              )
            ]),
      ),
    ));
  }
}
