import 'package:flutter/material.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedfundtransferfundtransferhistorywidget/generated/GeneratedGroup12792Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedfundtransferfundtransferhistorywidget/generated/GeneratedGroup12793Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedfundtransferfundtransferhistorywidget/generated/GeneratedBarsWidget9.dart';

/* Frame Fund Transfer / Fund Transfer History
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFundTransferFundTransferHistoryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 118.5,
                right: null,
                bottom: null,
                width: 375.0,
                height: 142.5,
                child: GeneratedGroup12792Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 422.0,
                child: GeneratedGroup12793Widget(),
              )
            ]),
      ),
    ));
  }
}
