import 'package:flutter/material.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedaccountinformationwidget/generated/GeneratedFrame12722Widget.dart';
import 'package:flutterapp/seylanmobilebankingappapp/generatedaccountinformationwidget/generated/GeneratedGroup12762Widget.dart';

/* Frame Account  Information
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAccountInformationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1170.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1170.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 3.0,
                              top: 272.0,
                              right: null,
                              bottom: null,
                              width: 370.0,
                              height: 893.0,
                              child: GeneratedFrame12722Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 252.0,
                              child: GeneratedGroup12762Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
